<?php

/**
 * Returns the importmap for this application.
 *
 * - "path" is a path inside the asset mapper system. Use the
 *     "debug:asset-map" command to see the full list of paths.
 *
 * - "entrypoint" (JavaScript only) set to true for any module that will
 *     be used as an "entrypoint" (and passed to the importmap() Twig function).
 *
 * The "importmap:require" command can be used to add new entries to this file.
 */
return [
    'app' => [
        'path' => './assets/app.js',
        'entrypoint' => true,
    ],
    'talent-tree' => [
        'path' => './assets/talent-tree.js',
        'entrypoint' => true,
    ],
    // Full ESM+compiler build (not "importmap:require vue", which pulls a runtime-only
    // build with no template compiler - our components use a string `template`). Committed
    // directly under assets/lib/ (not assets/vendor/, which is gitignored/regenerated by
    // AssetMapper) so a fresh checkout doesn't silently lose this - see gotchas.md.
    'vue' => [
        'path' => './assets/lib/vue.esm-browser.js',
    ],
];
